# Generated by Django 6.1.1 on 2026-10-05 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='nombre')),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('encargado', models.CharField(max_length=150, verbose_name='encargado')),
            ],
            options={
                'verbose_name': 'delegación',
                'verbose_name_plural': 'delegaciones',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='delegacione_nombre_cc5c7f_idx'), models.Index(fields=['encargado'], name='delegacione_encarga_982de5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('porcentaje', models.IntegerField(verbose_name='porcentaje')),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='delegaciones.delegacion', verbose_name='delegación')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
                'ordering': ['titulo'],
            },
        ),
    ]
