# Generated by Django 6.1.1 on 2026-10-05 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delegaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'vecino',
                'verbose_name_plural': 'vecinos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudVecinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True, verbose_name='folio')),
                ('nombre_ciudadano', models.CharField(max_length=150, verbose_name='nombre del ciudadano')),
                ('rut', models.CharField(max_length=20, verbose_name='RUT')),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('descripcion_problema', models.TextField(verbose_name='descripción del problema')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='fecha de ingreso')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Resuelto', 'Resuelto')], default='Pendiente', max_length=20, verbose_name='estado')),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vecinales', to='delegaciones.delegacion', verbose_name='delegación')),
            ],
            options={
                'verbose_name': 'solicitud vecinal',
                'verbose_name_plural': 'solicitudes vecinales',
                'ordering': ['-fecha_ingreso', '-id'],
                'indexes': [models.Index(fields=['estado'], name='solicitudes_estado_2efbf2_idx'), models.Index(fields=['delegacion', 'fecha_ingreso'], name='solicitudes_delegac_2d5ac9_idx'), models.Index(fields=['rut'], name='solicitudes_rut_3f6859_idx'), models.Index(fields=['folio'], name='solicitudes_folio_56090c_idx')],
            },
        ),
    ]
